//------------------------------------------------------------------------------
// <auto-generated>
//     Generated control declarations for AdminsReport.aspx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrbitechWeb
{
    public partial class AdminsReport
    {
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;
        protected global::System.Web.UI.WebControls.Literal ErrorLiteral;
        protected global::System.Web.UI.WebControls.DropDownList DdlRange;
        protected global::System.Web.UI.WebControls.Literal LitRevenue;
        protected global::System.Web.UI.WebControls.Literal LitOrderCount;
        protected global::System.Web.UI.WebControls.Literal LitAvgOrder;
        protected global::System.Web.UI.WebControls.Repeater MonthlyRepeater;
        protected global::System.Web.UI.WebControls.Repeater TopProductsRepeater;
        protected global::System.Web.UI.WebControls.Literal LitSatDelivery;
        protected global::System.Web.UI.WebControls.Literal LitSatProduct;
        protected global::System.Web.UI.WebControls.Literal LitSatPercent;
        protected global::System.Web.UI.WebControls.Literal LitSatResponses;
        protected global::System.Web.UI.WebControls.Repeater DistributionRepeater;
        protected global::System.Web.UI.WebControls.Repeater ComplaintsRepeater;
        protected global::System.Web.UI.WebControls.Panel NoComplaintsPanel;
    }
}
