//------------------------------------------------------------------------------
// <auto-generated>
//     Designer partial class for Contact.aspx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrbitechWeb
{
    public partial class Contact
    {
        protected global::System.Web.UI.WebControls.Panel StatusPanel;
        protected global::System.Web.UI.WebControls.Literal StatusLiteral;
        protected global::System.Web.UI.WebControls.TextBox CName;
        protected global::System.Web.UI.WebControls.TextBox CEmail;
        protected global::System.Web.UI.WebControls.DropDownList CSubject;
        protected global::System.Web.UI.WebControls.TextBox CMessage;
        protected global::System.Web.UI.WebControls.Button SubmitBtn;
    }
}
