//------------------------------------------------------------------------------
// <auto-generated>
//     Designer partial class for Default.aspx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrbitechWeb
{
    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Repeater FeaturedRepeater;
    }
}
