//------------------------------------------------------------------------------
// <auto-generated>
//     Generated control declarations for Feedback.aspx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrbitechWeb
{
    public partial class Feedback
    {
        protected global::System.Web.UI.WebControls.Literal LitAvgDeliveryDays;
        protected global::System.Web.UI.WebControls.Literal LitAvgDeliveryRating;
        protected global::System.Web.UI.WebControls.Literal LitAvgSatisfaction;
        protected global::System.Web.UI.WebControls.Literal LitPctSatisfied;
        protected global::System.Web.UI.WebControls.Panel StatusPanel;
        protected global::System.Web.UI.WebControls.Literal StatusLiteral;
        protected global::System.Web.UI.WebControls.TextBox TxtOrderID;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RfvOrderID;
        protected global::System.Web.UI.WebControls.CompareValidator CvOrderID;
        protected global::System.Web.UI.WebControls.RadioButtonList RblDelivery;
        protected global::System.Web.UI.WebControls.RadioButtonList RblSatisfaction;
        protected global::System.Web.UI.WebControls.TextBox TxtComments;
        protected global::System.Web.UI.WebControls.CheckBox ChkComplaint;
        protected global::System.Web.UI.WebControls.DropDownList DdlComplaintCategory;
        protected global::System.Web.UI.WebControls.Button BtnSubmitFeedback;
        protected global::System.Web.UI.WebControls.Repeater RecentFeedbackRepeater;
        protected global::System.Web.UI.WebControls.Panel NoReviewsPanel;
    }
}
