//------------------------------------------------------------------------------
// <auto-generated>
//     Designer partial class for Shop.aspx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrbitechWeb
{
    public partial class Shop
    {
        protected global::System.Web.UI.WebControls.Label PageTitleLabel;
        protected global::System.Web.UI.WebControls.Literal ProductCountLiteral;
        protected global::System.Web.UI.WebControls.Repeater ProductRepeater;
        protected global::System.Web.UI.WebControls.Panel NoResultsPanel;
    }
}
